Strings = {
    "ru": {
      "EnterPassword": "введите пароль",
      "WelcomeToRobco": "welcome to robco industries (tm) termlink",
      "LogonAdmin": " logon admin",
      "EntryDenied": "Отказ в доступе.",
      "Correct": "правильно.",
      "Allowance": "Пользование",
      "Replenished": "вновь разрешено.",
      "DudRemoved": "Предмет удален",
      "PleaseWait": "Пожалуйста,",
      "ExactMatch": "Точно!",
      "WhileSystem": "подождите",
      "IsAccessed": "входа в систему.",
      "InitLockout": "Блокировка начата.",
      "TerminalLocked": "терминал заблокирован",
      "PleaseContactAnAdministrator": "пожалуйста, свяжитесь с администратором",
      "RobcoIndustries": "robco industries (tm) termlink protocol",
      "LockoutImminent": "!!! предупреждение: терминал может быть заблокирован !!!",
      "AttemptsLeft": "{0} попытки осталось:",
      "Cursor": "█",
      "Square": "■",
      "SetTerminalInquire": "set terminal/inquire",
      "RITV300": "rit-v300",
      "SetFileProtectionOwner": "set file/protection=owner:rwed accounts.f",
      "SetHaltRestart": "set halt restart/maint",
      "BootAgentInfo": "Initializing Robco Industries(TM) MF Boot Agent v2.3.0\nRETROS BIOS\nRBIOS-4.02.08.00 52EE5.E7.E8\nCopyright 2201-2203 Robco Ind.\nUppermem: 64 KB\nRoot (5A8)\nMaintenance Mode",
      "RunDebugAccounts": "run debug/accounts.f",
      "TooHard": "Вы не можете взломать терминал уровня {0} с наукой {1}"
  
    },
    "en": {
      "EnterPassword": "enter password now",
      "WelcomeToRobco": "welcome to robco industries (tm) termlink",
      "LogonAdmin": " logon admin",
      "EntryDenied": "Entry denied.",
      "Correct": "correct.",
      "Allowance": "Allowance",
      "Replenished": "replenished.",
      "DudRemoved": "Dud removed.",
      "PleaseWait": "Please wait",
      "ExactMatch": "Exact match!",
      "WhileSystem": "while system",
      "IsAccessed": "is accessed.",
      "InitLockout": "Init lockout.",
      "TerminalLocked": "terminal locked",
      "PleaseContactAnAdministrator": "please, contact an administrator",
      "LockoutImminent": "!!! warning: lockout imminent !!!",
      "RobcoIndustries": "robco industries (tm) termlink protocol",
      "AttemptsLeft": "{0} attempt(s) left:",
      "Cursor": "█",
      "Square": "■",
      "SetTerminalInquire": "set terminal/inquire",
      "RITV300": "rit-v300",
      "SetFileProtectionOwner": "set file/protection=owner:rwed accounts.f",
      "SetHaltRestart": "set halt restart/maint",
      "BootAgentInfo": "Initializing Robco Industries(TM) MF Boot Agent v2.3.0\nRETROS BIOS\nRBIOS-4.02.08.00 52EE5.E7.E8\nCopyright 2201-2203 Robco Ind.\nUppermem: 64 KB\nRoot (5A8)\nMaintenance Mode",
      "RunDebugAccounts": "run debug/accounts.f",
      "TooHard": "You can't hack lvl {0} terminal with science lvl {1}"
    }
  };